### ISSUE TITLE
Semantic DOM Feedback!

### ISSUE THREAD

**Issue by mfehrenbach** [mikaarai/manuscript#1]
- [x] First off, what’s happening here? Mind your commits, only checking things in intentionally!

	<img width="203" alt="image" src="https://github.com/user-attachments/assets/a373b706-f5b9-463a-ad0b-8f0434b8addf">

- [x] Would move this intro into the `header`. Also the [`cite` would make sense](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite) around _Design of Everyday Things_ but not the entire para: 
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L7-L12

- [x] You could use `q` if you want to differentiate the [inline quotations](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q)
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L10-L10

- [x] We should only use [`br` in a semantic context](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br), not to add space (as I think they are here:
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L11
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L16
…etc.

- [x] These would make sense to group as [`section` elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)—and would let you differentiate/space in CSS:
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L17-L20

- [x] I would use `article` containers to differentiate the text and hour your response as “[self contained compositions](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article).” Likewise consistent `header` use between the two.

- [x] These should probably both be `h2`—you should only have one `h1` that is the [title for the whole page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page):
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L8
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L31

- [x] This should be [a `cite`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite):
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L33

- [x] But these should probably be `q`, or `blockquote` for the longer one:
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L34
https://github.com/mikaarai/manuscript/blob/45f5322ea827d537a74525e41bc1a54103b0b3b1/index.html#L37

Overall good start, but we want to see a lot more structure here both for semantics and to give yourself the ability to style it thoroughly! I might also consider how you can bring more variety (with inline tags) to both text and response.

✊

**Comment by mikaarai** [comment]
Just made all the updates per your suggestion. Thank you!
